action:
- data:
    message: Hubert w domu!
    data:
      push:
        sound: US-EN-Morgan-Freeman-Welcome-Home.wav
        badge: 5
  service: notify.telegram_hubert
alias: Hubert w domu
condition: []
id: '11'
initial_state: 'off'
trigger:
- entity_id: device_tracker.iphone
  platform: state
  to: home