- action:
  - data:
      message: New version {{ states.updater.updater.state }} of Home Assistant is
        available
    service: notify.ios_hubert
  alias: Update
  condition: []
  id: '1'
  trigger:
  - entity_id: updater.updater
    platform: state
- action:
  - data:
      message: Wilgotność paprotki poniżej 30%
    service: notify.ios_hubert
  - data:
      message: Wilgotność paprotki poniżej 30%
    service: notify.telegram_mysza
  alias: Nawodnienie paprotki
  condition: []
  id: '2'
  trigger:
  - below: '30'
    entity_id: sensor.paprotka_moisture
    platform: numeric_state
- action:
  - data:
      data:
        push:
          badge: 5
      message: Wilgotność fiołka w fioletowej doniczce poniżej 20%
    service: notify.ios_hubert
  - data:
      message: Wilgotność fiołka w fioletowej doniczce poniżej 20%
    service: notify.telegram_mysza
  alias: Nawodnienie fiołka w fioletowej doniczce
  condition: []
  id: '3'
  trigger:
  - below: '20'
    entity_id: sensor.fioek_1_moisture
    platform: numeric_state
- action:
  - data:
      message: Wilgotność fiołka w niebieskiej doniczce poniżej 20%
    service: notify.pushover
  - data:
      message: Wilgotność fiołka w niebieskiej doniczce poniżej 20%
    service: notify.telegram_mysza
  alias: Nawodnienie fiołka w niebieskiej doniczce
  condition: []
  id: '4'
  trigger:
  - below: '20'
    entity_id: sensor.fioek_2_moisture
    platform: numeric_state
- action:
  - data:
      message: Wilgotność fioletowego fiołka w ubranej doniczce poniżej 20%
    service: notify.pushover
  - data:
      message: Wilgotność fioletowego fiołka w ubranej doniczce poniżej 20%
    service: notify.telegram_mysza
  alias: Nawodnienie fiołka w sweterku
  condition: []
  id: '44'
  trigger:
  - below: '20'
    entity_id: sensor.fioek_fioletowy_moisture
    platform: numeric_state
- action:
  - data:
      message: Wilgotność Chamedory(palmy) poniżej 15%
    service: notify.pushover
  - data:
      message: Wilgotność Chamedory(palmy) poniżej 15%
    service: notify.telegram_mysza
  alias: Nawodnienie palmy
  condition: []
  id: '45'
  trigger:
  - below: '15'
    entity_id: sensor.chamedora_wytworna_moisture
    platform: numeric_state
- action:
  - data:
      message: Wilgotność Monstery poniżej 20%
    service: notify.pushover
  - data:
      message: Wilgotność Monstery poniżej 20%
    service: notify.telegram_mysza
  alias: Nawodnienie Monstery
  condition: []
  id: '46'
  trigger:
  - below: '20'
    entity_id: sensor.monstera_moisture
    platform: numeric_state
- action:
  - data:
      message: Home Assistant Start at {{ states('sensor.time') }}
    service: notify.pushover
  alias: Hass start
  condition: []
  id: '5'
  trigger:
  - event: start
    platform: homeassistant
- action:
  - data:
      message: Home Assistant Stop at {{ states('sensor.time') }}
    service: notify.pushover
  alias: Hass stop
  condition: []
  id: '6'
  trigger:
  - event: shutdown
    platform: homeassistant
- id: '7'
  alias: Prognoza
  trigger:
  - at: '19:00:00'
    platform: time
  condition: []
  action:
  - data:
      data:
        attachment:
          content-type: png
          hide-thumbnail: false
          url: http://meteo.org.pl/img/um/warszawa.png
      message: Prognoza na jutro {{ state('sensor.dark_sky_hourly_summary') }}
    service: notify.ios_hubert
  - data:
      message: Prognoza na jutro {{ states('sensor.pws_weather_2d_metric') }}
    service: notify.telegram_mysza
  - data:
      data:
        photo:
          url: http://meteo.org.pl/img/um/warszawa.png
      message: Prognoza na jutro {{ states('sensor.pws_weather_2d_metric') }}
    service: notify.telegram_mysza
- action:
  - data:
      name: screenshots
    service: frontend.set_theme
  alias: Set dark theme for night
  condition: []
  id: '8'
  initial_state: true
  trigger:
  - at: '19:00'
    platform: time
- action:
  - data:
      name: screenshots
    service: frontend.set_theme
  alias: Set light theme for day
  condition: []
  id: '9'
  initial_state: true
  trigger:
  - at: 08:00
    platform: time
- action:
  - data:
      message: Hubert w domu!
      data:
        push:
          sound: US-EN-Morgan-Freeman-Welcome-Home.wav
          badge: 5
    service: notify.telegram_hubert
  alias: Hubert w domu
  condition: []
  id: '11'
  initial_state: 'off'
  trigger:
  - entity_id: device_tracker.iphone
    platform: state
    to: home
- id: '1542017191318'
  alias: NAS ON
  trigger:
  - at: '12:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.nas
    service: switch.toggle
- id: '1542021191318'
  alias: MiFlora Low Battery - Chamedora
  trigger:
  - below: '20'
    entity_id: sensor.chamedora_wytworna_battery
    platform: numeric_state
  action:
  - data:
      message: Battery low in Chamedora {{ states('sensor.chamedora_wytworna_battery')
        }}%
      title: MiFlora Battery is low!
    service: notify.ios_hubert
- id: '1542698507632'
  alias: MiFlora Low Battery - Fikus
  trigger:
  - below: '20'
    entity_id: sensor.fioek_1_battery
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Battery low in Fikus {{ states('sensor.fioek_1_battery') }}%
      title: MiFlora Battery is low!
    service: notify.ios_hubert
- id: '1542698707903'
  alias: MiFlora Low Battery - Fiołek nieb. don.
  trigger:
  - below: '20'
    entity_id: sensor.fioek_2_battery
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Battery low in fiolek w niebieskiej doniczce {{ states('sensor.fioek_2_battery')
        }}%
      title: MiFlora Battery is low!
    service: notify.ios_hubert
- id: '1542699033721'
  alias: MiFlora Low Battery - Paprotka
  trigger:
  - below: '20'
    entity_id: sensor.paprotka_battery
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Battery low in paprotka {{ states('sensor.paprotka_battery') }}%
      title: MiFlora Battery is low!
    service: notify.ios_hubert
- id: '1542699087454'
  alias: MiFlora Low Battery - Monstera
  trigger:
  - below: '20'
    entity_id: sensor.monstera_battery
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Battery low in monstera {{ states('sensor.monstera_battery') }}%
      title: MiFlora Battery is low!
    service: notify.ios_hubert
- id: '1542699194980'
  alias: MiFlora Low Battery - Fiolek w sweterku
  trigger:
  - below: '20'
    entity_id: sensor.fioek_fioletowy_battery
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Battery low in fiołek w sweterku {{ states('sensor.fioek_fioletowy_battery')
        }}%
      title: MiFlora Battery is low!
    service: notify.ios_hubert
- id: '1542746506998'
  alias: Prognoza tygodniowa
  trigger:
  - at: '18:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - sun
  action:
  - data:
      message: Prognoza: {{states.sensor.dark_sky_daily_summary.state }}
      tittle: Prognoza na tydzień
    service: notify.pushover
