- action:
  - data:
      message: New version {{ states.updater.updater.state }} of Home Assistant is
        available
    service: notify.pushover
  - data:
      message: New version {{ states.updater.updater.state }} of Home Assistant is
        available
    service: notify.ios_hubert
  alias: Update
  condition: []
  id: '1'
  trigger:
  - entity_id: updater.updater
    platform: state
- action:
  - data:
      message: Wilgotność paprotki poniżej 25%
    service: notify.ios_hubert
  - data:
      message: Wilgotność paprotki poniżej 25%
    service: notify.telegram_mysza
  alias: Nawodnienie paprotki
  condition: []
  id: '2'
  trigger:
  - below: '25'
    entity_id: sensor.paprotka_moisture
    platform: numeric_state
- action:
  - data:
      message: Wilgotność fiołka w niebieskiej doniczce poniżej 25%
      data:
        push:
          badge: 5
    service: notify.ios_hubert
  - data:
      message: Wilgotność fiołka w niebieskiej doniczce poniżej 25%
    service: notify.telegram_mysza
  alias: Nawodnienie fiołka w niebieskiej doniczce
  condition: []
  id: '3'
  trigger:
  - below: '25'
    entity_id: sensor.fioek_1_moisture
    platform: numeric_state
- action:
  - data:
      message: Wilgotność fiołka w czerwonej doniczce poniżej 15%
    service: notify.pushover
  - data:
      message: Wilgotność fiołka w czerwonej doniczce poniżej 15%
    service: notify.telegram_mysza
  alias: Nawodnienie fiołka w czerwonej doniczce
  condition: []
  id: '4'
  trigger:
  - below: '15'
    entity_id: sensor.fioek_2_moisture
    platform: numeric_state
- action:
  - data:
      message: Home Assistant Start at {{ states('sensor.time') }}
    service: notify.pushover
  alias: Hass start
  condition: []
  id: '5'
  trigger:
  - event: start
    platform: homeassistant
- action:
  - data:
      message: Home Assistant Stop at {{ states('sensor.time') }}
    service: notify.pushover
  alias: Hass stop
  condition: []
  id: '6'
  trigger:
  - event: shutdown
    platform: homeassistant
- action:
#  - data:
#      message: Prognoza na jutro {{ states('sensor.pws_weather_2d_metric') }}
#    service: notify.ios_hubert
  - data:
      data:
        attachment:
          url: http://meteo.org.pl/img/um/warszawa.png
          content-type: png
          hide-thumbnail: false
      message: Prognoza na jutro {{ states('sensor.pws_weather_2d_metric') }}
    service: notify.ios_hubert
  - data:
      message: Prognoza na jutro {{ states('sensor.pws_weather_2d_metric') }}
    service: notify.telegram_myszaa
  - data:
      data:
        photo:
          url: http://meteo.org.pl/img/um/warszawa.png
      message: Prognoza na jutro {{ states('sensor.pws_weather_2d_metric') }}
    service: notify.telegram_myszaa
  alias: Prognoza
  condition: []
  id: '7'
  trigger:
  - at: '19:00:00'
    platform: time
- action:
  - data:
      name: screenshots
    service: frontend.set_theme
  alias: Set dark theme for night
  condition: []
  id: '8'
  initial_state: true
  trigger:
  - at: '19:00'
    platform: time
- action:
  - data:
      name: screenshots
    service: frontend.set_theme
  alias: Set light theme for day
  condition: []
  id: '9'
  initial_state: true
  trigger:
  - at: 08:00
    platform: time
- action:
  - data:
      message: Daria w domu!
    service: notify.telegram_hubert
  alias: Daria w domu
  condition: []
  id: '10'
  initial_state: 'off'
  trigger:
  - entity_id: device_tracker.myszowyiphone
    platform: state
    to: home
- action:
  - data:
      message: Hubert w domu!
      data:
        push:
          sound: "US-EN-Morgan-Freeman-Welcome-Home.wav"
          badge: 5
    service: notify.telegram_hubert
  alias: Hubert w domu
  condition: []
  id: '11'
  initial_state: 'off'
  trigger:
  - entity_id: device_tracker.iphone
    platform: state
    to: home
- action:
  - data:
      message: Daria wyszła z domu.
    service: notify.telegram_hubert
  alias: Daria wyszła
  condition: []
  id: '12'
  initial_state: 'off'
  trigger:
  - entity_id: device_tracker.myszowyiphone
    platform: state
    to: not_home
- action:
  - condition: state
    entity_id: vacuum.xiaomi_vacuum
    state: turn_on
  alias: Odkurzanie
  condition:
  - condition: state
    entity_id: device_tracker.iphone
    state: not home
  - condition: state
    entity_id: device_tracker.myszowyiphone
    state: not home
  id: '13'
  trigger:
  - entity_id: binary_sensor.workday_sensor
    platform: state
    to: 'on'
  - at: '10:00'
    platform: time
- action:
  - data:
      message: Hubert w pracy!
    service: notify.ios_hubert
  alias: New Automation
  condition: []
  id: '1'
  trigger:
  - entity_id: device_tracker.iphone
    platform: state
    to: Work
