- action:
  - data:
      message: New version {{ states.updater.updater.state }} of Home Assistant is
        available
    service: notify.pushover
  - data:
      message: New version {{ states.updater.updater.state }} of Home Assistant is
        available
    service: notify.telegram_hubert
  alias: Update
  condition: []
  id: '1505415052228'
  trigger:
  - entity_id: updater.updater
    platform: state
- action:
  - data:
      message: Wilgotność paprotki poniżej 25%
    service: notify.pushover
  - data:
      message: Wilgotność paprotki poniżej 25%
    service: notify.telegram_mysza
  alias: Nawodnienie paprotki
  condition: []
  id: '1505497053088'
  trigger:
  - below: '25'
    entity_id: sensor.paprotka_moisture
    platform: numeric_state
- action:
  - data:
      message: Wilgotność fiołka w niebieskiej doniczce poniżej 25%
    service: notify.pushover
  - data:
      message: Wilgotność fiołka w niebieskiej doniczce poniżej 25%
    service: notify.telegram_mysza
  alias: Nawodnienie fiołka w niebieskiej doniczce
  condition: []
  id: '1505497273631'
  trigger:
  - below: '25'
    entity_id: sensor.fioek_1_moisture
    platform: numeric_state
- action:
  - data:
      message: Wilgotność fiołka w czerwonej doniczce poniżej 15%
    service: notify.pushover
  - data:
      message: Wilgotność fiołka w czerwonej doniczce poniżej 15%
    service: notify.telegram_mysza
  alias: Nawodnienie fiołka w czerwonej doniczce
  condition: []
  id: '1505497412825'
  trigger:
  - below: '15'
    entity_id: sensor.fioek_2_moisture
    platform: numeric_state
- action:
  - data:
      message: Home Assistant Start at {{ states('sensor.time') }}
    service: notify.pushover
  alias: Hass start
  condition: []
  id: '1505499650244'
  trigger:
  - event: start
    platform: homeassistant
- action:
  - data:
      message: Home Assistant Stop at {{ states('sensor.time') }}
    service: notify.pushover
  alias: Hass stop
  condition: []
  id: '1505499713906'
  trigger:
  - event: shutdown
    platform: homeassistant
- action:
  - data:
      message: Prognoza na jutro {{ states('sensor.pws_weather_2d_metric') }}
    service: notify.telegram_hubert
  - data:
      data:
        photo:
          url: http://meteo.org.pl/img/um/warszawa.png
      message: Prognoza na jutro {{ states('sensor.pws_weather_2d_metric') }}
    service: notify.telegram_hubert
  - data:
      message: Prognoza na jutro {{ states('sensor.pws_weather_2d_metric') }}
    service: notify.telegram_mysza
  - data:
      data:
        photo:
          url: http://meteo.org.pl/img/um/warszawa.png
      message: Prognoza na jutro {{ states('sensor.pws_weather_2d_metric') }}
    service: notify.telegram_mysza
  alias: Prognoza
  condition: []
  id: '1505501013398'
  trigger:
  - at: '19:00:00'
    platform: time
- action:
  - data:
      name: screenshots
    service: frontend.set_theme
  alias: Set dark theme for night
  condition: []
  id: '1510777731207'
  initial_state: true
  trigger:
  - at: '19:00'
    platform: time
- action:
  - data:
      name: screenshots
    service: frontend.set_theme
  alias: Set light theme for day
  condition: []
  id: '1510779620059'
  initial_state: true
  trigger:
  - at: 08:00
    platform: time
- action:
  - data:
      message: Daria w domu!
    service: notify.telegram_hubert
  alias: Daria w domu
  condition: []
  id: '1516379923357'
  trigger:
  - entity_id: device_tracker.myszowyiphone
    platform: state
    to: home
- action:
  - data:
      message: Hubert w domu!
    service: notify.telegram_hubert
  alias: Hubert w domu
  condition: []
  id: '1516380844092'
  trigger:
  - entity_id: device_tracker.iphone
    platform: state
    to: home
- action:
  - data:
      message: Daria wyszła z domu.
    service: notify.telegram_hubert
  alias: Daria wyszła
  condition: []
  id: '1516607782012'
  trigger:
  - entity_id: device_tracker.myszowyiphone
    platform: state
    to: not_home
