homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 78
  unit_system: metric
  time_zone: Europe/Warsaw
  customize: !include_dir_merge_named customization

http:
# Uncomment this to add a password (recommended!)
# api_password: PASSWORD
frontend:
panel_iframe: !include panel_iframe/menu.yaml
sensor: !include_dir_list sensor/
binary_sensor: !include_dir_list binary_sensor/
switch: !include_dir_list switch/
influxdb: !include influx/influxdb.yaml
camera: !include_dir_list camera/
# Text to speech
# tts:
#  platform: google
notify: !include_dir_list notify/
mqtt: !include mqtt/hass.yaml
mysensors: !include mysensors/mysensors.yaml
zone: !include_dir_list zone/
group: !include_dir_merge_named group/
automation: !include_dir_list automation/
## Enables
updater:
# Discover some devices automatically
discovery:
# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:
# Enables support for tracking state changes over time.
# history:
# View all events in a logbook
# logbook:
sun: