homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 78
  unit_system: metric
  time_zone: Europe/Warsaw
  customize: !include customize.yaml

logger: !include logger.yaml
system_log:
  max_entries: 20

http:
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.0/24
    - 192.168.2.0/24
    - 192.168.4.0/24
# Uncomment this to add a password (recommended!)
# api_password: PASSWORD
frontend:
  themes: !include themes.yaml
config:
automation: !include automations.yaml
#Script is similar to automation
script:

panel_iframe: !include panel_iframe.yaml
binary_sensor: !include binary_sensors.yaml
sensor: !include_dir_merge_list sensor/
switch: !include_dir_list switch/
influxdb: !include influxdb.yaml
camera: !include cameras.yaml
notify: !include notify.yaml
mqtt: !include mqtt.yaml
zone: !include zone.yaml
group: !include groups.yaml
weblink: !include weblink.yaml
media_player: !include media_player.yaml
telegram_bot: !include telegram_bot.yaml
#mysensors: !include mysensors.yaml

#device_tracker:
#  - platform: mikrotik
#    host: 192.168.1.1
#    username: !secret mikrotik-user
#    password: !secret mikrotik-pass


#Enable iOS app
ios:

updater:
  reporting: true
# Discover some devices automatically
discovery:
# Text to speech - currently not using
#tts:
#  platform: google
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
#For sun automations
sun:
