homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 78
  unit_system: metric
  time_zone: Europe/Warsaw
  customize: !include_dir_merge_named customization

  http:
# Uncomment this to add a password (recommended!)
# api_password: PASSWORD
# Uncomment this if you are using SSL or running in Docker etc
# base_url: example.duckdns.org:8123

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
  frontend:
  panel_iframe:
    router:
      title: 'Router'
      icon: 'mdi:router-wireless'
      url: 'http://192.168.1.1'
    staty:
      title: 'Statystyki'
      icon: 'mdi:chart-line'
      url: 'http://192.168.1.1/graphs/iface/Orange-FFTH/'
    nas:
      title: 'NAS'
      icon: 'mdi:harddisk'
      url: 'http://192.168.1.2'

  sensor: !include_dir_list sensor/

  switch: !include_dir_list switch/

  influxdb: !include influx/influxdb.yaml

  camera: !include_dir_list camera/

# Text to speech
# tts:
#  platform: google

  notify: !include_dir_list notify/

  mqtt: !include mqtt/hass.yaml

# mysensors: !include mysensors/mysensors.yaml

  zone: !include_dir_list zone/

  group: !include_dir_merge_named group/
 
## Enables
  updater:
# Discover some devices automatically
  discovery:
# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:
# Enables support for tracking state changes over time.
# history:
# View all events in a logbook
  logbook:
# Track the sun
# sun:
