homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 78
  unit_system: metric
  time_zone: Europe/Warsaw
  customize: !include customize.yaml

logger: !include logger.yaml

system_log:
  max_entries: 20

http:
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.0/24
    - 192.168.2.0/24
    - 192.168.4.0/24
  server_port: 8123
  ip_ban_enabled: True
# Uncomment this to add a password (recommended!)
# api_password: PASSWORD

# This offers the official frontend to control Home Assistant.
frontend:
  themes: !include themes.yaml

config:
automation old: !include automations.yaml
automation: !include_dir_list automation/
#Script is similar to automation
script:

panel_iframe: !include panel_iframe.yaml
binary_sensor: !include binary_sensors.yaml
sensor: !include_dir_merge_list sensor/
switch: !include_dir_list switch/
influxdb: !include influxdb.yaml
input_select: !include input_select.yaml
camera: !include cameras.yaml
notify: !include notify.yaml
mqtt: !include mqtt.yaml
zone: !include zone.yaml
group: !include groups.yaml
weblink: !include weblink.yaml
telegram_bot: !include telegram_bot.yaml
device_tracker: !include device_tracker.yaml
weather: !include weather.yaml

#IKEA Trådfri setup preparation
tradfri:
  host: 192.168.1.8
  allow_tradfri_groups: true

# Enable iOS app
ios:
homekit: 
  filter:
    include_entities:
      - sensor.bme680_sensor_pressure
      - sensor.bme680_sensor_humidity
      - sensor.bme680_sensor_temperature
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_humidity
      - sensor.dark_sky_pressure
      - sensor.dark_sky_temperature
      - sensor.dark_sky_wind_speed
      - switch.ledy
      - switch.nas
      - switch.pc
      - switch.pihole
      - switch.speakers
    exclude_domains:
      - automations
      - device_tracker
      - group
      - switch
      - weather
      - weblink
      - zone
      - sun
      - sensor
    include_domains:
      - light

#  pincode: !secret homekit

updater:
  reporting: true

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv

# For sun automations
sun:

# This offers a map on the frontend
map:
