action:
- data:
  message: Wilgotność fioletowego fiołka w ubranej doniczce poniżej 20%
  service: notify.pushover
- data:
  message: Wilgotność fioletowego fiołka w ubranej doniczce poniżej 20%
  service: notify.telegram_mysza
alias: Nawodnienie fiołka w sweterku
condition: []
id: '44'
trigger:
  below: '20'
  entity_id: sensor.fioek_fioletowy_moisture
  platform: numeric_state