action:
  - data:
      message: Wilgotność Chamedory(palmy) poniżej 15%
    service: notify.pushover
  - data:
      message: Wilgotność Chamedory(palmy) poniżej 15%
    service: notify.telegram_mysza
alias: Nawodnienie palmy
condition: []
id: '45'
trigger:
  below: '15'
  entity_id: sensor.chamedora_wytworna_moisture
  platform: numeric_state