action:
  data:
    message: Wilgotność fiołka w niebieskiej doniczce poniżej 20%
  service: notify.pushover
  data:
    message: Wilgotność fiołka w niebieskiej doniczce poniżej 20%
  service: notify.telegram_mysza
alias: Nawodnienie fiołka w niebieskiej doniczce
condition: []
id: '4'
trigger:
  below: '20'
  entity_id: sensor.fioek_2_moisture
  platform: numeric_state