action:
- data:
  message: Wilgotność Monstery poniżej 20%
  service: notify.pushover
- data:
  message: Wilgotność Monstery poniżej 20%
  service: notify.telegram_mysza
alias: Nawodnienie Monstery
condition: []
id: '46'
trigger:
  below: '20'
  entity_id: sensor.monstera_moisture
  platform: numeric_state