action:
  data:
    data:
      push:
        badge: 5
    message: Wilgotność fiołka w fioletowej doniczce poniżej 20%
  service: notify.ios_hubert
  data:
    message: Wilgotność fiołka w fioletowej doniczce poniżej 20%
  service: notify.telegram_mysza
alias: Nawodnienie fiołka w fioletowej doniczce
condition: []
id: '3'
trigger:
  below: '20'
  entity_id: sensor.fioek_1_moisture
  platform: numeric_state