id: '1542746506998'
alias: Prognoza tygodniowa
trigger:
  at: '18:00'
  platform: time
# condition:
# - condition: time
#   weekday:
#   - sun
action:
  data:
#    message: Prognoza na jutro {{ states('sensor.pws_weather_2d_metric') }}
    message: >-
      {{ states('sensor.dark_sky_temperature')|round(0) }}C na zewnątrz oraz {{ states('sensor.dark_sky_daily_summary')|lower }}
  service: notify.pushover