id: '1542746506998'
alias: Prognoza tygodniowa
trigger:
  at: '18:00'
  platform: time
condition: []
action:
- data:
    message: >-
      Aktualnie {{ states('sensor.dark_sky_temperature')|round(0) }}C na zewnątrz oraz {{ states('sensor.dark_sky_daily_summary')|lower }}
  service: notify.telegram_hubert
- data:
    data:
      photo:
        - url: http://meteo.org.pl/img/um/warszawa.png
          caption: ICM
    message: >-
      Aktualnie {{ states('sensor.dark_sky_temperature')|round(0) }}C na zewnątrz oraz {{ states('sensor.dark_sky_daily_summary')|lower }}
  service: notify.telegram_hubert