id: '1542746506998'
alias: Prognoza tygodniowa
trigger:
  at: '18:00'
  platform: time
condition: []
action:
- data:
    message: Prognoza
    data:
      photo:
        - url: http://meteo.org.pl/img/um/warszawa.png
          caption: ICM
  service: notify.telegram_hubert
- data:
    tittle: Prognoza
    message: >-
      Aktualnie {{ states('sensor.dark_sky_temperature')|round(0) }}C na zewnątrz oraz {{ states('sensor.dark_sky_daily_summary')|lower }}
     



# condition:
# - condition: time
#   weekday:
#   - sun
#action:
#  data:
#    message: >-
#      {{ Aktualnie states('sensor.dark_sky_temperature')|round(0) }}C na zewnątrz oraz {{ states('sensor.dark_sky_daily_summary')|lower }}
#    title: "Pogoda"
#  service: notify.telegram_hubert

#action:
#- data:
#    message: >-
#      {{ Aktualnie states('sensor.dark_sky_temperature')|round(0) }}C na zewnątrz oraz {{ states('sensor.dark_sky_daily_summary')|lower }}
#  service: notify.telegram_hubert
#- data:
#    data:
#      photo:
#        url: http://meteo.org.pl/img/um/warszawa.png
#    message: Prognoza na jutro {{ states('sensor.pws_weather_2d_metric') }}
#  service: notify.telegram_hubert


