id: '1542746506998'
alias: Prognoza tygodniowa
trigger:
  at: '18:00'
  platform: time
# condition:
# - condition: time
#   weekday:
#   - sun
action:
  data:
    data:
      file:
        url: http://meteo.org.pl/img/um/warszawa.png
    message: >-
      {{ Aktualnie states('sensor.dark_sky_temperature')|round(0) }}C na zewnątrz oraz {{ states('sensor.dark_sky_daily_summary')|lower }}
    title: "Pogoda"
  service: notify.pushover