- platform: bme680
  name: BME680 Sensor
  i2c_bus: 1
  i2c_address: 0x77
  monitored_conditions:
    - temperature
    - humidity
    - pressure
    - gas
    - airquality
  oversampling_temperature: 8
  oversampling_humidity: 2
  oversampling_pressure: 4
  filter_size: 3
  gas_heater_temperature: 320
  gas_heater_duration: 150
  aq_burn_in_time: 300
  aq_humidity_baseline: 40
  aq_humidity_bias: 25