- platform: miflora
  mac: "C4:7C:8D:62:A8:4D"
  name: Fiołek_1
  force_update: false
  median: 5
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery
- platform: miflora
  mac: "C4:7C:8D:62:E0:EE"
  name: Fiołek_2
  force_update: false
  median: 5
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery
- platform: miflora
  mac: "C4:7C:8D:62:E0:FD"
  name: Paprotka
  force_update: false
  median: 5
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery