- platform: snmp
  name: System
  host: 192.168.1.1
  community: public
  baseoid: 1.3.6.1.2.1.1.1.0

- platform: snmp
  name: Uptime
  host: 192.168.1.1
  community: public
  baseoid: 1.3.6.1.2.1.1.3.0
