- platform: snmp
  name: System
  host: 192.168.1.1
  community: public
  baseoid: 1.3.6.1.2.1.1.1.0

- platform: snmp
  name: Uptime
  host: 192.168.1.1
  community: public
  baseoid: 1.3.6.1.2.1.1.3.0

- platform: snmp
  name: Mikrotik temperature
  host: 192.168.1.1
  community: public
  baseoid: 1.3.6.1.4.1.14988.1.1.3.10.0

- platform: snmp
  name: WAN TX
  host: 192.168.1.1
  community: public
  baseoid: 1.3.6.1.4.1.14988.1.1.14.1.1.61.2
# baseoid: 1.3.6.1.2.1.2.2.1.16.2

- platform: snmp
  name: WAN RX
  host: 192.168.1.1
  community: public
  baseoid: 1.3.6.1.4.1.14988.1.1.14.1.1.31.2
# baseoid: 1.3.6.1.2.1.2.2.1.10.2

