### Component to monitor travis-ci status of config file repro.
- platform: travisci
  api_key: !secret travisci_api_key
  repository: 
    - ".homeassistant"
  monitored_conditions:
    - last_build_id
    - last_build_state
