- platform: wunderground
  api_key: !secret api_wunderground
  pws_id: IWARSAW104
  lang: "PL"
  monitored_conditions:
    - weather
    - UV
    - relative_humidity
    - wind_dir
    - dewpoint_c
    - temp_c
    - feelslike_c
    - wind_kph
    - wind_gust_kph
    - precip_today_metric
    - visibility_km
    - solarradiation
    - elevation
    - location
    - station_id
    - weather_1d_metric
    - weather_1n_metric
    - weather_2d_metric
    - weather_2n_metric
    - weather_3d_metric
    - weather_3n_metric
    - weather_4d_metric
    - weather_4n_metric
