- platform: ztm
  api_key: !secret ztm_api_key
  entries: 3
  lines:
    - number: 182
      bus_stop_id: 2102
      bus_stop_number: "03"
    - number: 158
      bus_stop_id: 2102
      bus_stop_number: "03"