- alias: 'Send notification when soil moisture is too low'
  trigger:
    platform: numeric_state
    entity_id: sensor.czujnik_wilgoci_gleby_2_0
    value_template: '{{ state.attributes.V_HUM }}'
    below: 55
  action:
    service: notify.pushover
    data:
      message: 'Wilgotność awokado poniżej 55%.'