- alias: 'Powiadomienie o wschodzie słońca'
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:00:00'
  action:
    service: notify.pushover
    data:
      message: 'Wschód słońca.'
- alias: 'Powiadomienie o wschodzie słońca'
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  action:
    service: notify.pushover
    data:
      message: 'Zachód słońca za godzinę.'
- alias: 'Turn a few lights on when the sun gets dim'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 3.5
  action:
    service: switch.turn_on
    entity_id: switch.ledy